---
title: "Ruaha_Katavi"
author: "Caroline Williams"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
vignette: >
  %\VignetteIndexEntry{Ruaha_Katavi}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Libraries
```{r}
library(raster)
library(sf)
```

## Read Boundary SA Shapefile
```{r}
RKL <- st_read("C:/Users/Caroline/Documents/Graduate Courses/Spring 2021 Courses/GEOG 382/Project/WCS/inst/extdata/boundary/RKL.shp")
```

## Read WorldClim data
```{r}
# import precipitation 2000-2009 & 2010 to 2018  
# set working directory to where data is located
setwd("D:/WCS/data/precip/")

# list files based on prefix
precip_list = list.files(getwd(), pattern="wc2.1_2.5m_prec_") 

# Create raster stack
precip_r <- stack(precip_list)
names(precip_r)   
```

## Clip Climate data to Ruaha-Katavki boundary
```{r}
# clip precipitation 2000 - 2018 to study area
precip_crop <- crop(precip_r, RKL) # crop to extent
precip_clip <- mask(precip_crop, RKL) # mask cropped data to study area
```

## Climate Spatial Analysis
### Precipitation Annual Mean Monthly
```{r}
# 2000 Annual Mean
# create raster stack subset for 2000
p_2000 <- raster::subset(precip_clip, 1:12)

# calculate mean precipitation for 2000
precip_2000 <- calc(p_2000, fun = mean, na.rm = T)

# 2001 Annual Mean
# create raster stack subset for 2001
p_2001 <- raster::subset(precip_clip, 13:24)

# calculate mean precipitation for 2001
precip_2001 <- calc(p_2001, fun = mean, na.rm = T)

# 2002 Annual Mean
# create raster stack subset for 2002
p_2002 <- raster::subset(precip_clip, 25:36)

# calculate mean precipitation for 2002
precip_2002 <- calc(p_2002, fun = mean, na.rm = T)

# 2003 Annual Mean
# create raster stack subset for 2003
p_2003 <- raster::subset(precip_clip, 37:48)

# calculate mean precipitation for 2003
precip_2003 <- calc(p_2003, fun = mean, na.rm = T)

# 2004 Annual Mean
# create raster stack subset for 2004
p_2004 <- raster::subset(precip_clip, 49:60)

# calculate mean precipitation for 2004
precip_2004 <- calc(p_2004, fun = mean, na.rm = T)

# 2005 Annual Mean
# create raster stack subset for 2005
p_2005 <- raster::subset(precip_clip, 61:72)

# calculate mean precipitation for 2005
precip_2005 <- calc(p_2005, fun = mean, na.rm = T)

# 2006 Annual Mean
# create raster stack subset for 2006
p_2006 <- raster::subset(precip_clip, 73:84)

# calculate mean precipitation for 2006
precip_2006 <- calc(p_2006, fun = mean, na.rm = T)

# 2007 Annual Mean
# create raster stack subset for 2007
p_2007 <- raster::subset(precip_clip, 85:96)

# calculate mean precipitation for 2007
precip_2007 <- calc(p_2007, fun = mean, na.rm = T)

# 2008Annual Mean
# create raster stack subset for 2008
p_2008 <- raster::subset(precip_clip, 97:108)

# calculate mean precipitation for 2008
precip_2008 <- calc(p_2008, fun = mean, na.rm = T)

# 2009 Annual Mean
# create raster stack subset for 2009
p_2009 <- raster::subset(precip_clip, 109:120)

# calculate mean precipitation for 2009
precip_2009 <- calc(p_2009, fun = mean, na.rm = T)

# 2010 Annual Mean
# create raster stack subset for 2010
p_2010 <- raster::subset(precip_clip, 121:132)

# calculate mean precipitation for 2010
precip_2010 <- calc(p_2010, fun = mean, na.rm = T)

# 2011 Annual Mean
# create raster stack subset for 2011
p_2011 <- raster::subset(precip_clip, 133:144)

# calculate mean precipitation for 2011
precip_2011 <- calc(p_2011, fun = mean, na.rm = T)

# 2012 Annual Mean
# create raster stack subset for 2012
p_2012 <- raster::subset(precip_clip, 145:156)

# calculate mean precipitation for 2012
precip_2012 <- calc(p_2012, fun = mean, na.rm = T)

# 2013 Annual Mean
# create raster stack subset for 2013
p_2013 <- raster::subset(precip_clip, 157:168)

# calculate mean precipitation for 2013
precip_2013 <- calc(p_2013, fun = mean, na.rm = T)

# 2014 Annual Mean
# create raster stack subset for 2014
p_2014 <- raster::subset(precip_clip, 169:180)

# calculate mean precipitation for 2014
precip_2014 <- calc(p_2014, fun = mean, na.rm = T)

# 2015 Annual Mean
# create raster stack subset for 2015
p_2015 <- raster::subset(precip_clip, 181:192)

# calculate mean precipitation for 2015
precip_2015 <- calc(p_2015, fun = mean, na.rm = T)

# 2016 Annual Mean
# create raster stack subset for 2016
p_2016 <- raster::subset(precip_clip, 193:204)

# calculate mean precipitation for 2016
precip_2016 <- calc(p_2016, fun = mean, na.rm = T)

# 2017 Annual Mean
# create raster stack subset for 2017
p_2017 <- raster::subset(precip_clip, 205:216)

# calculate mean precipitation for 2017
precip_2017 <- calc(p_2017, fun = mean, na.rm = T)

# 2018 Annual Mean
# create raster stack subset for 2018
p_2018 <- raster::subset(precip_clip, 217:228)

# calculate mean precipitation for 2018
precip_2018 <- calc(p_2018, fun = mean, na.rm = T)
```

### Mean Precipitation 2000 - 2018
```{r}
# create raster stack of mean annual precipitation
p_2000_2018 <- stack(precip_2000, precip_2001, precip_2002, precip_2003, precip_2004, precip_2005, precip_2006, precip_2007, precip_2008, precip_2009, precip_2010, precip_2011, precip_2012, precip_2013, precip_2014, precip_2015, precip_2016, precip_2017, precip_2018)

# calculate mean precipitation 2000 to 2018
precip_2000_2018 <- calc(p_2000_2018, fun = mean, na.rm = T)
```

### Export Processed data
```{r}
writeRaster(precip_2000, "D:/WCS/data/precip/r_outputs/precip_annual_2000.rst", overwrite = TRUE)
writeRaster(precip_2001, "D:/WCS/data/precip/r_outputs/precip_annual_2001.rst", overwrite = TRUE)
writeRaster(precip_2002, "D:/WCS/data/precip/r_outputs/precip_annual_2002.rst", overwrite = TRUE)
writeRaster(precip_2003, "D:/WCS/data/precip/r_outputs/precip_annual_2003.rst", overwrite = TRUE)
writeRaster(precip_2004, "D:/WCS/data/precip/r_outputs/precip_annual_2004.rst", overwrite = TRUE)
writeRaster(precip_2005, "D:/WCS/data/precip/r_outputs/precip_annual_2005.rst", overwrite = TRUE)
writeRaster(precip_2006, "D:/WCS/data/precip/r_outputs/precip_annual_2006.rst", overwrite = TRUE)
writeRaster(precip_2007, "D:/WCS/data/precip/r_outputs/precip_annual_2007.rst", overwrite = TRUE)
writeRaster(precip_2008, "D:/WCS/data/precip/r_outputs/precip_annual_2008.rst", overwrite = TRUE)
writeRaster(precip_2009, "D:/WCS/data/precip/r_outputs/precip_annual_2009.rst", overwrite = TRUE)
writeRaster(precip_2010, "D:/WCS/data/precip/r_outputs/precip_annual_2010.rst", overwrite = TRUE)
writeRaster(precip_2011, "D:/WCS/data/precip/r_outputs/precip_annual_2011.rst", overwrite = TRUE)
writeRaster(precip_2012, "D:/WCS/data/precip/r_outputs/precip_annual_2012.rst", overwrite = TRUE)
writeRaster(precip_2013, "D:/WCS/data/precip/r_outputs/precip_annual_2013.rst", overwrite = TRUE)
writeRaster(precip_2014, "D:/WCS/data/precip/r_outputs/precip_annual_2014.rst", overwrite = TRUE)
writeRaster(precip_2015, "D:/WCS/data/precip/r_outputs/precip_annual_2015.rst", overwrite = TRUE)
writeRaster(precip_2016, "D:/WCS/data/precip/r_outputs/precip_annual_2016.rst", overwrite = TRUE)
writeRaster(precip_2017, "D:/WCS/data/precip/r_outputs/precip_annual_2017.rst", overwrite = TRUE)
writeRaster(precip_2018, "D:/WCS/data/precip/r_outputs/precip_annual_2018.rst", overwrite = TRUE)
```

